#                             #
#   GoodbyeMobs by: tweedjt   #
#                             #
debug_logging: false

#Set the radius around players with GBM on
Protection_Radius: 25

#Enable Knockback on mobs instead of deleting them
knockback_enabled: false

#Message prefix for plugin
message_prefix: "&d[&fGoodByeMobs&d] &r"

