name: GoodbyeMobs
author: tweedjt
version: 1.0
api-version: 1.13
main: me.tweedjt.goodbyemobs.GoodbyeMobs
commands:
  gbm:
    description: Adds or removes you from the GoodByeMobs list
    usage: /gbm