#                           #
#   AutoPickup by: tweedjt   #
#                           #

#Are Drops to Inventory on by default
auto_pickup: true

pvp_drops: true

auto_monster_drops: true

auto_animal_drops: true

auto_block_drops: true

Drop_Glass: true

Drop_EXP: true


#On message for /as command
autosmelt_on_message: AutoPickup has been turned &aON

#Off message for /as command
autosmelt_off_message: AutoPickup has been turned &aOFF

#Message prefix for plugin
message_prefix: "&d[&fAutoPickup&d] &r"